spring.datasource.url = jdbc:postgresql://localhost:5432/DioceseFranca
spring.datasource.username = postgres
spring.datasource.password = santos

spring.datasource.driver-class-name=org.postgresql.Driver